Iss hipcms 89
HiP-App/HiPCMS-OnlyOfficeIntegration pull request #23
Opened 2016-12-13 13:00 UTC by maltehol

2016-12-13 14:48 UTC, janis-kra reviewed
Lots of eslint errors, I'll fix it with `eslint app.js --fix`

2016-12-13 15:11 UTC, janis-kra requested changes

2016-12-13 15:11 UTC, janis-kra commented on bin/www
> +var app = require('../app-compiled');
app-compiled does not exist and is created nowhere - I guess you forgot to commit some kind of build script.

Why would we need to compile anyway? I dont think there is any fancy ES7 stuff that we use, so node v6 should be able to run it all

2016-12-13 15:11 UTC, janis-kra commented on permissions.js
> +  if (!error && response.statusCode == 200) {
always use `===` in javascript

2016-12-13 15:11 UTC, janis-kra commented on permissions.js
> +  if (!error && response.statusCode == 401) {
see above

2016-12-13 15:11 UTC, janis-kra commented on permissions.js
> +var permissions = {};
always use `const` if possible

2016-12-14 16:35 UTC, maltehol commented on app.js
> +  for (let i = 0; i < arguments.length; i + 1) {
Why not i++?

2016-12-14 16:41 UTC, janis-kra commented on app.js
> +  for (let i = 0; i < arguments.length; i + 1) {
Our eslint config wants it that way (see http://eslint.org/docs/rules/no-plusplus).
We can of course just change the config, not a big deal.

2016-12-14 16:54 UTC, janis-kra commented on app.js
> +  for (let i = 0; i < arguments.length; i + 1) {
I'll merge this now, feel free to change the config separately if you want.

2016-12-14 16:54 UTC, janis-kra approved these changes

2016-12-14 16:55 UTC, merged